import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  await prisma.tour.deleteMany()

  const tours = [
    {
      name: 'Angra dos Reis e Ilha Grande',
      slug: 'angra-dos-reis',
      category: 'EXCURSION',
      shortDesc: 'Paraíso en el Caribe Brasileño con paseo en barco temático, DJ y paradas en playas vírgenes.',
      fullDesc: 'Viví el Caribe Brasileño en Angra dos Reis. A 160 km de Río, un paseo en barco con DJ te lleva a las Ilhas Botinas, Lagoa Azul y Praia de Japariz. Un día completo de naturaleza, mar turquesa y descanso.',
      duration: 'Aprox. 14 horas',
      schedule: 'Salidas diarias · Embarque 07:00–08:00 · Regreso aprox. 21:00',
      includes: ['Transporte ejecutivo', 'Barco temático con DJ', 'Almuerzo buffet', 'Guía bilingüe'],
      excludes: ['Tasa de embarque R$25', 'Bebidas y postres', 'Snorkel, chalecos y fotos'],
      extras: 'A bordo: Bar bistró, áreas instagramables, snorkel y servicio de fotos.',
      notes: 'No se permiten coolers ni bebidas externas. Itinerario sujeto a clima.',
      childPolicy: 'Menores de 0–4 años gratis · 5–10 años 50% de descuento',
      paymentMethods: ['Efectivo', 'Pix', 'Débito', 'Crédito (+5%)'],
      featured: true,
    },
    {
      name: 'Búzios',
      slug: 'buzios',
      category: 'EXCURSION',
      shortDesc: 'El destino favorito de Brigitte Bardot con paseo en barco por sus playas más exclusivas.',
      fullDesc: 'Descubrí Búzios con un paseo en barco por Armação, Ossos, Azeda, João Fernandes, Tartaruga y más. Después, tiempo libre para explorar la famosa Rua das Pedras con boutiques y restaurantes.',
      duration: 'Aprox. 12 horas',
      schedule: 'Salidas diarias · Embarque 07:00–08:00 · Regreso aprox. 21:00',
      includes: ['Transporte', 'Paseo en barco 2h30', 'Almuerzo buffet', 'Guía bilingüe'],
      excludes: ['Tasa de embarque R$10', 'Bebidas y postres', 'Snorkel y máscaras', 'Fotos subacuáticas'],
      notes: 'Si el paseo en barco se cancela por clima: reembolso R$20 o tour en jardineira según disponibilidad. Llevar traje de baño, bloqueador y agua.',
      childPolicy: 'Menores de 5 años gratis · hasta 10 años 50% de descuento',
      paymentMethods: ['Efectivo', 'Pix', 'Débito', 'Crédito (+5%)'],
      featured: true,
    },
    {
      name: 'Arraial do Cabo',
      slug: 'arraial-do-cabo',
      category: 'EXCURSION',
      shortDesc: 'El Caribe Brasileño con aguas cristalinas, cuevas azules y playas paradisíacas.',
      fullDesc: 'Conocé Arraial do Cabo: playas de arena blanca y aguas turquesas que no tienen nada que envidiarle al Caribe. El paseo en barco incluye 3 paradas: Prainhas do Pontal, Praia do Farol y Praia do Forno, con vistas a la Gruta Azul y el Perfil do Gorila.',
      duration: 'Aprox. 14 horas',
      schedule: 'Salidas diarias · Embarque 07:00–08:00 · Regreso aprox. 21:00',
      includes: ['Transporte ida y vuelta', 'Paseo en escuna', 'Almuerzo buffet', 'Guía bilingüe'],
      excludes: ['Tasa de embarque R$15', 'Traslado estacionamiento→muelle R$16', 'Bebidas y postres', 'Snorkel y fotos subacuáticas'],
      notes: 'Puede haber demoras de embarque. Paseo sujeto a clima. En caso de cancelación del barco: reembolso R$20 o tour terrestre.',
      childPolicy: 'Menores de 5 años gratis · 5–10 años 50% de descuento',
      paymentMethods: ['Efectivo', 'Pix', 'Débito', 'Crédito (+5%)'],
      featured: true,
    },
    {
      name: 'City Tour Río de Janeiro',
      slug: 'city-tour',
      category: 'CITY',
      shortDesc: 'Los íconos de Río en un solo día: Cristo Redentor, Maracanã, Selarón y más.',
      fullDesc: 'El recorrido definitivo por los puntos más emblemáticos de la Ciudad Maravillosa. Cristo Redentor con entrada incluida, Maracanã, Sambódromo, las coloridas Escaleras de Selarón, los Arcos de Lapa y la Catedral Metropolitana.',
      duration: 'Aprox. 6 horas (08:00 a 14:00)',
      schedule: 'Salidas diarias · Recogida en hospedaje',
      includes: ['Transporte ida y vuelta en van ejecutiva', 'Recogida en hospedaje', 'Entrada Cristo Redentor', 'Almuerzo buffet', 'Guía bilingüe en español'],
      excludes: ['Bebidas y postres'],
      childPolicy: 'Consultar tarifa para menores de 10 años',
      paymentMethods: ['Efectivo', 'Pix', 'Débito', 'Crédito en un pago (+5% extranjero)'],
      featured: false,
    },
    {
      name: 'Un Día en Río de Janeiro',
      slug: 'un-dia-en-rio',
      category: 'CITY',
      shortDesc: 'Cristo Redentor + Pan de Azúcar + los íconos de Río en un tour completo de 8 horas.',
      fullDesc: 'La experiencia completa de Río: subís al Cristo Redentor en tren, disfrutás la vista 360° desde el Pan de Azúcar en teleférico, pasás por el Maracaná, el Sambódromo, Selarón, la Catedral y los Arcos de Lapa. Todo en un día, con almuerzo buffet incluido.',
      duration: 'Aprox. 8 horas',
      schedule: 'Salidas diarias · Embarque desde 07:00 · Regreso 18:00',
      includes: ['Transporte ida y vuelta', 'Entrada Cristo Redentor', 'Teleférico Pan de Azúcar', 'Almuerzo buffet', 'Guía bilingüe'],
      excludes: ['Bebidas y postres'],
      childPolicy: 'Consultar precios para menores',
      paymentMethods: ['Efectivo', 'Pix', 'Débito', 'Crédito (+5%)'],
      featured: true,
    },
    {
      name: 'AquaRio + Boulevard Olímpico',
      slug: 'aquario-boulevard',
      category: 'CULTURAL',
      shortDesc: 'El acuario más grande de Sudamérica y el paseo de arte urbano más vibrante de Río.',
      fullDesc: 'Caminá por el túnel transparente del AquaRio rodeado de especies marinas y luego recorré el Boulevard Olímpico con sus 3,2 km de murales étnicos del artista Kobra. Un plan ideal para toda la familia.',
      duration: 'Aprox. 4 horas (09:00 a 13:00)',
      schedule: 'Salidas diarias',
      includes: ['Transporte ida y vuelta en vehículo ejecutivo', 'Entrada al AquaRio', 'Guía bilingüe'],
      excludes: ['Entrada al Museu do Amanhã', 'Entrada Rio Star', 'Comidas y bebidas'],
      childPolicy: 'Hasta 2 años: gratis',
      paymentMethods: ['Efectivo', 'Pix', 'Crédito/Débito (+5%)'],
      featured: false,
    },
    {
      name: 'Estadio Maracanã por Dentro',
      slug: 'maracana',
      category: 'CULTURAL',
      shortDesc: 'Acceso exclusivo a los bastidores del estadio más famoso del mundo.',
      fullDesc: 'Viví la magia del Maracanã desde adentro: vestuarios, sala de prensa, exposiciones con camisetas de Pelé y Garrincha, y los espacios donde nacieron los momentos más grandes del fútbol mundial.',
      duration: 'A confirmar',
      schedule: 'Salidas diarias · Embarque en Zona Sur, Botafogo y Centro',
      includes: ['Transporte ida y vuelta', 'Entrada al Maracanã', 'Guía bilingüe especializado'],
      excludes: [],
      childPolicy: 'Consultar',
      paymentMethods: ['Consultar'],
      featured: false,
    },
    {
      name: 'Petrópolis – La Ciudad Imperial',
      slug: 'petropolis',
      category: 'EXCURSION',
      shortDesc: 'Historia, arquitectura imperial y chocolate en la ciudad más elegante de la Serra.',
      fullDesc: 'Un día entre palacios, catedrales y la historia del Brasil Imperial. Museo Imperial, Palácio Quitandinha, Catedral de São Pedro, Palácio de Cristal, Casa de Santos Dumont y la clásica parada en la Cervejaria Bohemia con degustación opcional.',
      duration: 'Aprox. 10–12 horas',
      schedule: 'Salidas diarias · Embarque 07:00–09:00 desde Zona Sur y Centro',
      includes: ['Transporte ida y vuelta con aire acondicionado', 'Almuerzo', 'Guía bilingüe acreditado'],
      excludes: ['Postres y bebidas', 'Degustación en Bohemia', 'Fotos profesionales'],
      childPolicy: 'Menores de 5 años gratis · 6–10 años 50% de descuento',
      paymentMethods: ['Efectivo', 'Débito', 'Crédito (recargo adicional)'],
      featured: false,
    },
    {
      name: 'Tour Favela Rocinha',
      slug: 'favela-rocinha',
      category: 'CULTURAL',
      shortDesc: 'Recorrido seguro y guiado por la favela más grande de Latinoamérica.',
      fullDesc: 'Conocé la riqueza cultural de Rocinha: caminatas por sus calles, feria de artesanía local y mirador con vista panorámica de Río. Una experiencia auténtica y humana con guía acreditado bilingüe.',
      duration: 'A confirmar',
      schedule: 'Salidas diarias · Embarque 13:00–14:00 desde Zona Sur',
      includes: ['Traslado ida y vuelta', 'Guía bilingüe acreditado'],
      excludes: ['Alimentación, fotos y servicios extra', 'Tasa de la comunidad R$10 por persona'],
      notes: 'Seguir las indicaciones del guía en todo momento. Mantener respeto hacia los residentes.',
      childPolicy: 'Consultar',
      paymentMethods: ['Consultar'],
      featured: false,
    },
    {
      name: 'Vuelo en Helicóptero',
      slug: 'helicoptero',
      category: 'NAUTICO',
      shortDesc: 'Río desde el aire: Cristo, Pan de Azúcar, Ipanema y Copacabana en vuelos de 15 a 60 min.',
      fullDesc: 'La perspectiva más impresionante de Río. Cuatro rutas disponibles (15–60 min) que cubren Zona Sur, Cristo Redentor, Pan de Azúcar, Lagoa, Maracanã y Bahía de Guanabara. También disponible vuelo sin puertas para fotos únicas.',
      duration: 'Desde 15 hasta 60 minutos según ruta',
      schedule: 'A confirmar según disponibilidad',
      includes: ['Vuelo en helicóptero según ruta elegida'],
      excludes: ['Traslado al helipuerto'],
      extras: 'Ruta 1 (15–20 min): Barra, Pedra da Gávea, Ipanema, Cristo · Ruta 2 (25–30 min): agrega Copacabana, Pan de Azúcar · Ruta 3 (40–45 min): ciudad completa · Ruta 4 (55–60 min): Niterói y Guanabara · Sin puertas (30–35 min): especial fotos.',
      childPolicy: 'Consultar',
      paymentMethods: ['Consultar'],
      featured: true,
    },
    {
      name: 'Pedra do Telégrafo',
      slug: 'pedra-do-telegrafo',
      category: 'AVENTURA',
      shortDesc: 'El mirador viral de Río con fotos épicas y vistas al mar, la naturaleza y la montaña.',
      fullDesc: 'Conocida por sus fotos que simulan adrenalina extrema, Pedra do Telégrafo combina trekking de nivel medio (1,5 km) con vistas increíbles a Grumari, Prainha y toda la Zona Oeste de Río. Ideal para los que buscan algo diferente.',
      duration: '6 a 8 horas',
      schedule: 'Salidas por la mañana · Embarque 06:00–07:00 desde Zona Sur y Centro',
      includes: ['Traslado ida y vuelta', 'Guía turístico acreditado'],
      excludes: ['Alimentación, bebidas y postres', 'Fotos profesionales'],
      notes: 'Llevar agua, protector solar, repelente y calzado cómodo. No se permiten coolers. Apto para mayores de 10 años. Visibilidad sujeta al clima.',
      childPolicy: 'Apto para mayores de 10 años',
      paymentMethods: ['Consultar'],
      featured: false,
    },
    {
      name: 'Paseo en Lancha + Jet Ski',
      slug: 'lancha-jet-ski',
      category: 'NAUTICO',
      shortDesc: 'Un día en el mar carioca en lancha privada para hasta 15 personas, con parrilla incluida.',
      fullDesc: 'Navegá la costa de Río en una lancha amplia para 15 personas. La ruta Urca → Praia Vermelha → Adão e Eva → Praia do Morcego incluye paradas para nadar, música bluetooth, alfombra flotante y un marinero que prepara la barbacoa a bordo.',
      duration: 'Hasta 6 horas',
      schedule: 'A coordinar según disponibilidad',
      includes: ['Marinero a bordo', 'Combustible', 'Hielera + hielo', 'Carbón', 'Parrilla y kit completo', 'Sistema de sonido bluetooth', 'Alfombra flotante'],
      excludes: ['Alimentos para la parrilla', 'Bebidas'],
      notes: 'Capacidad máxima: 15 pasajeros.',
      childPolicy: 'Consultar',
      paymentMethods: ['Consultar'],
      featured: false,
    },
    {
      name: 'Amanecer Stand Up Paddle',
      slug: 'sup-amanecer',
      category: 'AVENTURA',
      shortDesc: 'Remá al amanecer en Copacabana y verás salir el sol desde el mar. Experiencia única.',
      fullDesc: 'Una de las experiencias más memorables de Río: remada de 1h30 en el mar de Copacabana justo cuando sale el sol (aprox. 5:30). Podés remar sentado, de rodillas o de pie. Incluye instrucción, chaleco y acompañamiento durante toda la actividad.',
      duration: '1h30 de actividad · Horario 04:40 a 06:00',
      schedule: 'Lunes a viernes R$190 · Sábados, domingos y feriados R$200 · Cupos limitados',
      includes: ['Instrucción técnica', 'Guarda-volúmenes', 'Chaleco salvavidas', 'Acompañamiento durante la actividad'],
      excludes: ['Traslado al punto de encuentro'],
      notes: 'Llegar a la playa a las 4:20. Requiere agendamiento previo.',
      priceAdult: 190,
      childPolicy: 'Consultar',
      paymentMethods: ['Consultar'],
      featured: false,
    },
    {
      name: 'Morro Dois Irmãos + Vidigal',
      slug: 'morro-dois-irmaos',
      category: 'AVENTURA',
      shortDesc: 'Trekking con vistas panorámicas de Río, Rocinha y la Zona Sur desde la cima.',
      fullDesc: 'Uno de los trekkings más espectaculares de Río: subís al Morro Dois Irmãos con vista 360° sobre Ipanema, Leblon, la Lagoa y Rocinha. Podés elegir amanecer, día pleno o atardecer. El precio incluye guía, mototaxi para el ascenso e ingreso a la reserva.',
      duration: 'Varía según opción elegida',
      schedule: 'Amanecer: 03:00 · Día pleno: 07:00–13:00 · Atardecer: 16:30 · Punto de encuentro: Sheraton Grand Rio',
      includes: ['Guía especializado', 'Mototaxi para el ascenso', 'Ingreso a la reserva', 'Tasa de turismo local'],
      excludes: ['Alimentación y bebidas'],
      childPolicy: 'Consultar',
      paymentMethods: ['Consultar'],
      featured: false,
    },
  ]

  for (const tour of tours) {
    await prisma.tour.create({ data: tour as any })
  }

  console.log(`✅ Seed completado: ${tours.length} tours creados`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
